### ISSUE TITLE
cannot load such file -- active_job/logging (LoadError)

### ISSUE THREAD

**Issue by gottfrois** [rocketjob/rails_semantic_logger#108]
### Environment

* Ruby `2.6.6`
* Rails `5.2.2`
* Semantic Logger `~> 4.4`
* Rails Semantic Logger `4.4.4`

Rails is loaded with the following frameworks:

```ruby
require "rails"
require "active_model/railtie"
require "active_record/railtie"
```

Exception stacktrace:

```
Traceback (most recent call last):
	46: from bin/rails:4:in `<main>'
	45: from bin/rails:4:in `require'
	44: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
	43: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	42: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	41: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	40: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	39: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	38: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/commands/console/console_command.rb:95:in `perform'
	37: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	36: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
	35: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	34: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	33: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	32: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	31: from /Users/gottfrois/Code/textmaster-root/services/option_presets_service/config/environment.rb:5:in `<top (required)>'
	30: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	29: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	28: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	27: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	26: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	25: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
	24: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
	23: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	22: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	21: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	20: from /Users/gottfrois/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	19: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	18: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	17: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	16: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/railties-5.2.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
	15: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	14: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
	13: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	12: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	11: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	10: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	 9: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/engine.rb:141:in `block in <class:Engine>'
	 8: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 7: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 6: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	 5: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 4: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/extensions/active_job/logging.rb:2:in `<top (required)>'
	 3: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 2: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/gottfrois/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- active_job/logging (LoadError)
```

### Expected Behavior

When loading a rails application without ActiveJob, RailsSemanticLogger should not raise an exception trying to load the missing gem.

### Actual Behavior

When loading a rails application without ActiveJob, RailsSemanticLogger raise an exception when trying to load `active_job/logging`.

### Possible Fix

I think the issue comes from this code:

```ruby
require("rails_semantic_logger/extensions/active_job/logging") if defined?(ActiveJob)
```
https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L139

`ActiveJob` here refers to `RailsSemanticLogger::ActiveJob` which is correctly defined. Instead, I believe here we want to check whether the active_job dependency is loaded and refer to `::ActiveJob`.

**Comment by rodzyn** [comment]
Hi @reidmorrison, since it's solved in the master and the version seems to be bumped... Can we expect the `4.4.5` to be pushed to rubygems?
