### ISSUE TITLE
Rails fails to start if log level of trace is used with v4.4.5

### ISSUE THREAD

**Issue by rmm5t** [rocketjob/rails_semantic_logger#112]
### Environment

* Ruby Version: 2.5.8
* Rails Version: 6.0.3.4
* Semantic Logger Version: 4.7.4
* Rails Semantic Logger Version: 4.4.5
* Other Application/framework names and versions (e.g. Puma, etc.): Puma 
* Rails configuration:

```
  # config/environments/development.rb
  config.log_level = :trace
```

### Expected Behavior

This is the behavior with rails_semantic_logger v4.4.4

```
$ bin/rails server
=> Booting Puma
=> Rails 6.0.3.4 application starting in development 
=> Run `rails server --help` for more startup options
2020-12-01 16:14:39.318224 D [5318:70326763605520] Sidekiq -- Sidekiq client with redis options {:url=>"redis://localhost:6379/3"}
Puma starting in single mode...
* Version 4.3.6 (ruby 2.5.8-p224), codename: Mysterious Traveller
* Min threads: 1, max threads: 1
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
```

### Actual Behavior

This is the behavior after upgrading to rails_semantic_logger v4.4.5
```
$ bin/rails server
=> Booting Puma
=> Rails 6.0.3.4 application starting in development 
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	20: from bin/rails:4:in `<main>'
	19: from /path/app/vendor/ruby/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	18: from /path/app/vendor/ruby/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	17: from /path/app/vendor/ruby/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	16: from /path/app/vendor/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	15: from /path/app/vendor/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	14: from /path/app/vendor/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	13: from /path/app/vendor/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	12: from /path/app/vendor/ruby/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	11: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'
	10: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	 9: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	 8: from /path/app/vendor/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 7: from /path/app/vendor/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 6: from /path/app/vendor/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 5: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	 4: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
	 3: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	 2: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:37:in `start'
	 1: from /path/app/vendor/ruby/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:81:in `log_to_stdout'
/Users/mcgear/.rbenv/versions/2.5.8/lib/ruby/2.5.0/logger.rb:284:in `level=': invalid log level: trace (ArgumentError)
```

**Comment by reidmorrison** [comment]
Reverted a pull request in 4.4.5. Please try v4.4.6 and re-open this ticket if you still see the issue.

**Comment by rmm5t** [comment]
@reidmorrison This worked for Rails 6.0, but upgrading to Rails 6.1.1, the server still runs, but the console fails:

```
$ bin/rails s
=> Booting Puma
=> Rails 6.1.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
2021-01-15 15:55:08.652987 D [19958:4460] Sidekiq -- Sidekiq client with redis options {:url=>"redis://localhost:6379/6"}
Puma starting in single mode...
* Version 4.3.7 (ruby 2.7.2-p137), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
```

```
$ bin/rails c
Running via Spring preloader in process 20152
Traceback (most recent call last):
  36: from -e:1:in `<main>'
  35: from /Users/mcgear/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  34: from /Users/mcgear/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  33: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:26:in `fork'
  32: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
  31: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
  30: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
  29: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
  28: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
  27: from /Users/mcgear/app/bin/rails:5:in `<main>'
  26: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
  25: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  24: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  23: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  22: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  21: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  20: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
  19: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/command.rb:50:in `invoke'
  18: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/command/base.rb:69:in `perform'
  17: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  16: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  15: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  14: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/commands/console/console_command.rb:102:in `perform'
  13: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/commands/console/console_command.rb:19:in `start'
  12: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/commands/console/console_command.rb:19:in `new'
  11: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/commands/console/console_command.rb:35:in `initialize'
  10: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/engine.rb:449:in `load_console'
   9: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/application.rb:541:in `run_console_blocks'
   8: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/engine/railties.rb:15:in `each'
   7: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/engine/railties.rb:15:in `each'
   6: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/application.rb:541:in `block in run_console_blocks'
   5: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/railtie.rb:250:in `run_console_blocks'
   4: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/railtie.rb:275:in `each_registered_block'
   3: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/railtie.rb:275:in `each'
   2: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/railties-6.1.1/lib/rails/railtie.rb:250:in `block in run_console_blocks'
   1: from /Users/mcgear/app/vendor/ruby/2.7.0/ruby/2.7.0/gems/activerecord-6.1.1/lib/active_record/railtie.rb:60:in `block in <class:Railtie>'
/Users/mcgear/.rbenv/versions/2.7.2/lib/ruby/2.7.0/logger.rb:268:in `level=': invalid log level: trace (ArgumentError)
```

**Comment by rmm5t** [comment]
@reidmorrison Friendly nudge just in case you might have a good idea of the underlying root cause of this. If you have an idea for a direction to poke around in, I might have time in next week or so to take a look.
