### ISSUE TITLE
Could not log "sql.active_record" event in Rails 6.1 when query has IN clause

### ISSUE THREAD

**Issue by aldavidson** [rocketjob/rails_semantic_logger#121]
### Environment

* Ruby Version 2.7.2p137
* Rails Version 6.1.1
* Semantic Logger Version 4.7.4
* Rails Semantic Logger Version 4.4.6
* Other Application/framework names and versions (e.g. Puma, etc.)  puma. [Gemfile is here](https://github.com/DFE-Digital/get-help-with-tech/blob/main/Gemfile)
* Relevant part of the Rails configuration in our repo: [config/initializers/semantic_logger.rb](https://github.com/DFE-Digital/get-help-with-tech/blob/main/config/initializers/semantic_logger.rb)

* Full Stack Trace:

```
[84112:puma threadpool 002 log_subscriber.rb:118] ActiveRecord -- Could not log "sql.active_record" event. NoMethodError: undefined method `type' for "new":String 
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/active_record/log_subscriber.rb:150:in `render_bind_v5_0_3'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/active_record/log_subscriber.rb:112:in `block in bind_values_v5_1_5'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/active_record/log_subscriber.rb:111:in `map'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/active_record/log_subscriber.rb:111:in `bind_values_v5_1_5'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/active_record/log_subscriber.rb:33:in `sql'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/subscriber.rb:150:in `finish'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/log_subscriber.rb:115:in `finish'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/fanout.rb:157:in `finish'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/fanout.rb:63:in `block in finish'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/fanout.rb:63:in `each'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/fanout.rb:63:in `finish'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:688:in `log'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:676:in `exec_no_cache'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `execute_and_clear'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:53:in `exec_query'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `block in select_all'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:308:in `block in execute_simple_calculation'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/relation.rb:868:in `skip_query_cache_if_necessary'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:308:in `execute_simple_calculation'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:269:in `perform_calculation'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:144:in `calculate'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:51:in `count'
/home/al/projects/DFE-Digital/get-help-with-tech/app/views/computacenter/home/show.html.erb:26:in `_app_views_computacenter_home_show_html_erb__2983401246196144344_86280'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/base.rb:247:in `public_send'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/base.rb:247:in `_run'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/template.rb:154:in `block in render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:205:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/template.rb:345:in `instrument_render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/template.rb:152:in `render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:203:in `block in instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:203:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:205:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/rendering.rb:117:in `block in _render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/base.rb:273:in `in_rendering_context'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/rendering.rb:116:in `_render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/rendering.rb:103:in `render_to_body'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/abstract_controller/rendering.rb:25:in `render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/rendering.rb:36:in `render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/abstract_controller/base.rb:228:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actiontext-6.1.1/lib/action_text/rendering.rb:20:in `with_renderer'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actiontext-6.1.1/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.1/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:203:in `block in instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/notifications.rb:203:in `instrument'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/abstract_controller/base.rb:165:in `process'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.1/lib/action_view/rendering.rb:39:in `process'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal.rb:190:in `dispatch'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_controller/metal.rb:254:in `dispatch'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/journey/router.rb:32:in `each'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.1/lib/active_record/migration.rb:601:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:87:in `protected_app_call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:82:in `better_errors_call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:60:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:132:in `call_app'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:28:in `block in call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `catch'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rails_semantic_logger-4.4.6/lib/rails_semantic_logger/rack/logger.rb:28:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/al/projects/DFE-Digital/get-help-with-tech/lib/middleware/secure_cookies.rb:19:in `call'
/home/al/projects/DFE-Digital/get-help-with-tech/lib/middleware/prevent_host_header_poisoning.rb:15:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/static.rb:24:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-raven-3.1.1/lib/raven/integrations/rack.rb:51:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/engine.rb:539:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/configuration.rb:246:in `call'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/request.rb:76:in `block in handle_request'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/request.rb:75:in `handle_request'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/server.rb:431:in `process_client'
/home/al/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/thread_pool.rb:145:in `block in spawn_thread'

```

### Expected Behavior

On Rails 6.0, for the example that threw the exception above, we get this line in the log:

2021-01-19 13:33:28.549474 D [87304:puma threadpool 004] (7.359ms) ActiveRecord -- {:sql=>"SELECT COUNT(*) FROM \"schools\" WHERE \"schools\".\"status\" = $1 AND (\"schools\".\"computacenter_change\" IN ($2, $3) OR \"schools\".\"computacenter_reference\" IS NULL)", :binds=>{:status=>"open", :computacenter_change=>["new", "amended"]}}

### Actual Behavior

On Rails 6.1, we get the exception above.

### Pull Request

I haven't identified a fix yet, but have added a [test case which reliably reproduces the issue: https://github.com/rocketjob/rails_semantic_logger/pull/120](https://github.com/rocketjob/rails_semantic_logger/pull/120/files#diff-44e809a7cf73a8ba7289b6a9d8e716f1e3329ae072fa977550198585628f4fecR80)

**Comment by aldavidson** [comment]
After some further research, it looks like this will be addressed in Rails if and when [PR 41068](https://github.com/rails/rails/pull/41068 ) makes it into a future release. Hopefully this won't be too long
