### ISSUE TITLE
gives error message when log file does not exist with semantic logger 3.3 Works fine with 3.1

### ISSUE THREAD

**Issue by timuckun** [rocketjob/rails_semantic_logger#14]
Just an FYI when 3.3 is released.

BTW it actually gives this error even if the file exists and has the right permissions.

```bash
2016-04-11 10:08:44.094278 T [14802:SemanticLogger::AppenderThread] SemanticLogger::Appender::File -- V3.3.0 Appender thread active
2016-04-11 10:08:44.094424 W [14802:70115773506000 base.rb:19] Rails -- Rails Error: Unable to access log file. Please ensure that /Users/tim/Documents/mhn/source/pgdw/log/development.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed. -- Exception: ArgumentError: Unknown options: {:multiline=>false}
/Users/tim/.gem/ruby/2.2.3/bundler/gems/semantic_logger-6939a43eb3a8/lib/semantic_logger/formatters/base.rb:19:in `initialize'
/Users/tim/.gem/ruby/2.2.3/bundler/gems/semantic_logger-6939a43eb3a8/lib/semantic_logger/formatters/color.rb:20:in `initialize'
/Users/tim/.gem/ruby/2.2.3/gems/rails_semantic_logger-3.1.1/lib/rails_semantic_logger/railtie.rb:77:in `new'
/Users/tim/.gem/ruby/2.2.3/gems/rails_semantic_logger-3.1.1/lib/rails_semantic_logger/railtie.rb:77:in `block in <class:Railtie>'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `call'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/Users/tim/Documents/mhn/source/pgdw/config/environment.rb:5:in `<top (required)>'
/Users/tim/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/tim/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/Users/tim/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tim/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:67:in `console'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by reidmorrison** [comment]
Please upgrade both rails_semantic_logger and semantic_logger to the newly published v3.3 gems.
It will resolve the error above.
