### ISSUE TITLE
undefined method `current_tags' for nil:NilClass with Rails 4.2 with ActiveModelSerializers v0.10.0.rc5

### ISSUE THREAD

**Issue by pietschy** [rocketjob/rails_semantic_logger#17]
From my gemfile 
```
gem 'active_model_serializers', github: 'rails-api/active_model_serializers', tag: 'v0.10.0.rc5'
```

```
2016-04-28 17:11:12.727557 F [90816:2172420880 debug_exceptions.rb:7] Rails -- Exception: NoMethodError: undefined method `current_tags' for nil:NilClass
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/active_model_serializers-2da361f16357/lib/active_model_serializers/logging.rb:102:in `logger_tagged_by_active_model_serializers?'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/active_model_serializers-2da361f16357/lib/active_model_serializers/logging.rb:94:in `tag_logger'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/active_model_serializers-2da361f16357/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_render_callbacks'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/active_model_serializers-2da361f16357/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
/Users/andrew/light_architect_web/app/serializers/base_serializer.rb:4:in `serialize'
```

Any thoughts?

**Comment by reidmorrison** [comment]
I added direct support for the above gem to Rails Semantic Logger. Please modify the line in Gemfile and try the code in master and let us know if it resolves the above issue:

~~~ruby
gem 'rails_semantic_logger', git: 'https://github.com/rocketjob/rails_semantic_logger.git'
~~~

**Comment by pietschy** [comment]
Thanks @reidmorrison, using master I'm now getting a different error.

```
2016-05-10 09:54:52.586794 F [61681:2206247160 debug_exceptions.rb:7] Rails -- Exception: NameError: undefined local variable or method `logger' for #<ActiveModelSerializers::SerializableResource:0x0000010f2dc2c8>
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/rails_semantic_logger-a8ab710f6735/lib/rails_semantic_logger/extensions/active_model_serializers/logging.rb:7:in `tag_logger'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/active_model_serializers-2da361f16357/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_render_callbacks'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/andrew/.rvm/gems/ruby-2.1.1@coolon_light_manager/bundler/gems/active_model_serializers-2da361f16357/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
/Users/andrew/light_architect_web/app/serializers/base_serializer.rb:4:in `serialize'
```

**Comment by reidmorrison** [comment]
The problem is that the Rails API ActiveModelSerializers gem makes incorrect assumptions about logging. I applied another possible change to the patch, but without actual code to try it out we do not know if it will sufficiently patch ActiveModelSerializers.

The example documentation for ActiveModelSerializers is very long and does not appear to have any simple examples that we can just use to confirm ActiveModelSerializers is working properly after the monkey patch.

Can you submit sample code that will run in a Rails console, or ideally submit a test in a PR that we can use to test that any patches applied to ActiveModelSerializers will work?

**Comment by reidmorrison** [comment]
I suspect the latest changes in master will work.

For an example of what we are looking for in a test, please see: https://github.com/rocketjob/rails_semantic_logger/blob/master/test/active_job_test.rb

**Comment by kevintyll** [comment]
Rails Semantic Logger 2.5 does still generate the error NameError: undefined local variable or method `logger' for #<ActiveModelSerializers::SerializableResource:0x0000010f2dc2c8>.

I'll submit a PR shortly that fixes it.
