### ISSUE TITLE
ActiveRecord not logging properly

### ISSUE THREAD

**Issue by jasantunes** [rocketjob/rails_semantic_logger#33]
Using regular logging, I should get something like:
```
  ActiveRecord::SchemaMigration Load (1.5ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
  User Load (2.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 637242267  ORDER BY `users`.`id` ASC LIMIT 1
  Role Load (1.9ms)  SELECT `roles`.* FROM `roles` INNER JOIN `users_roles` ON `roles`.`id` = `users_roles`.`role_id` WHERE `users_roles`.`user_id` = 637242267
```

But instead, I'm getting:
```
2017-04-07 14:14:06.999558 E [43197:70206873811960 log_subscriber.rb:85] ActiveRecord::Base -- Could not log "sql.active_record" event. TypeError: no implicit conversion of Hash into String ["/Users/joao/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/bundler/gems/octopus-a138b9363163/lib/octopus/log_subscriber.rb:17:in `+'", "/Users/joao/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/bundler/gems/octopus-a138b9363163/lib/octopus/log_subscriber.rb:17:in `debug_with_octopus_shard'", "/Users/joao/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/rails_semantic_logger-4.0.0/lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb:36:in `sql'", "/Users/joao/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.7/lib/active_support/subscriber.rb:100:in `finish'", "/Users/ (...)
```

The issue in particular seems to be caused by `Could not log "sql.active_record" event. TypeError: no implicit conversion of Hash into String`.

I'm using the gem without any configuration.

**Comment by reidmorrison** [comment]
Looking at the stack trace it is blowing up in octopus ( whatever that is) not semantic logger

**Comment by jasantunes** [comment]
I don't get any errors if I don't use `semantic_logger` though (see regular logging output I pasted first).

**Comment by reidmorrison** [comment]
You will have to patch octopus to make it work with semantic logger. See the code in this gem to patch rails to make it work.

**Comment by reidmorrison** [comment]
Looking at the octopus monkey patch code, you will definitely have to patch its patch to the log subscriber.

https://github.com/thiagopradi/octopus/blob/master/lib/octopus/log_subscriber.rb

Even better, octopus should use `logger.tagged` instead of patching the logger since that is what it is designed for. Or, even use the rails `config.log_tags` option to set the tag.

Closing the ticket since this is outside the scope of Semantic Logger.
