### ISSUE TITLE
Exception: NoMethodError: undefined method `call' for :default:Symbol

### ISSUE THREAD

**Issue by atomaka** [rocketjob/rails_semantic_logger#41]
Ruby 2.3.3, Rails 5.1.1, Rails Semantic Logger: 4.1.2, Semantic Logger: 4.1.1, No configuration

The default install of rails_semantic_logger is triggering errors in log files. I reverted to 4.1.1 to see if the error was present and it is not. I believe this problem is rails_semantic_logger since reverting to 4.1.1 for rails_semantic_logger without changing the semantic_logger version corrects the error, but I have not had an opportunity to investigate thoroughly. Logs included for actual and expected

ACTUAL (rails_semantic_logger 4.1.2)

```
2017-06-15 20:44:35.748368 E [1:SemanticLogger::Processor] SemanticLogger -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::File:0x00563291684588 @log=#<IO:<STDOUT>>, @formatter=:default, @application=nil, @host=nil, @filter=nil, @name="SemanticLogger::Appender::File", @level_index=nil, @level=nil> -- Exception: NoMethodError: undefined
method `call' for :default:Symbol
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/appender/file.rb:101:in `log'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:225:in `block in call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `each'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:150:in `process_requests'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:7:in `block in start'
2017-06-15 20:44:35.748084 D [1:puma 005] Rack -- Started -- {:method=>"GET", :path=>"/ping", :ip=>"172.22.0.1"}
2017-06-15 20:44:35.877003 E [1:SemanticLogger::Processor] SemanticLogger -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::File:0x00563291684588 @log=#<IO:<STDOUT>>, @formatter=:default, @application=nil, @host=nil, @filter=nil, @name="SemanticLogger::Appender::File", @level_index=nil, @level=nil> -- Exception: NoMethodError: undefined
method `call' for :default:Symbol
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/appender/file.rb:101:in `log'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:225:in `block in call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `each'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:150:in `process_requests'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:7:in `block in start'
2017-06-15 20:44:35.876823 D [1:puma 005] (0.768ms) ActiveRecord::Base -- {:sql=>"SELECT \"schema_migrations\".\"version\" FROM \"schema_migrations\" ORDER BY \"schema_migrations\".\"version\" ASC"}
2017-06-15 20:44:36.030428 E [1:SemanticLogger::Processor] SemanticLogger -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::File:0x00563291684588 @log=#<IO:<STDOUT>>, @formatter=:default, @application=nil, @host=nil, @filter=nil, @name="SemanticLogger::Appender::File", @level_index=nil, @level=nil> -- Exception: NoMethodError: undefined
method `call' for :default:Symbol
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/appender/file.rb:101:in `log'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:225:in `block in call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `each'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:150:in `process_requests'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:7:in `block in start'
2017-06-15 20:44:36.030264 D [1:puma 005] V1::PingsController -- Processing #show
2017-06-15 20:44:36.095865 E [1:SemanticLogger::Processor] SemanticLogger -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::File:0x00563291684588 @log=#<IO:<STDOUT>>, @formatter=:default, @application=nil, @host=nil, @filter=nil, @name="SemanticLogger::Appender::File", @level_index=nil, @level=nil> -- Exception: NoMethodError: undefined
method `call' for :default:Symbol
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/appender/file.rb:101:in `log'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:225:in `block in call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `each'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:223:in `call_appenders'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:150:in `process_requests'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/processor.rb:7:in `block in start'
2017-06-15 20:44:36.095255 I [1:puma 005] (64.5ms) V1::PingsController -- Completed #show -- {:controller=>"V1::PingsController", :action=>"show", :format=>"JSON", :method=>"GET", :path=>"/ping", :status=>204, :view_runtime=>0.0, :db_runtime=>0.0, :status_message=>"No Content"}
```

Expected (rails_semantic_logger 4.1.1)

```
2017-06-15 20:37:47.265632 D [1:puma 005] Rack -- Started -- {:method=>"GET", :path=>"/ping", :ip=>"172.22.0.1"}
2017-06-15 20:37:47.404282 D [1:puma 005] (0.824ms) ActiveRecord::Base -- {:sql=>"SELECT \"schema_migrations\".\"version\" FROM \"schema_migrations\" ORDER BY \"schema_migrations\".\"version\" ASC"}
2017-06-15 20:37:47.582106 D [1:puma 005] V1::PingsController -- Processing #show
2017-06-15 20:37:47.645568 I [1:puma 005] (63.3ms) V1::PingsController -- Completed #show -- {:controller=>"V1::PingsController", :action=>"show", :format=>"JSON", :method=>"GET", :path=>"/ping", :status=>204, :view_runtime=>0.0, :db_runtime=>0.0, :status_message=>"No Content"}
```

**Comment by atomaka** [comment]
It turns out I am running one relevant configuration option:

```
config.colorize_logging = false
```

Removing this configuration option corrects the error.   I haven't investigated further.

**Comment by reidmorrison** [comment]
Thank you for letting me know. I pushed a new gem to fix this issue.
