### ISSUE TITLE
Rails 5.1.5: Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by enrico** [rocketjob/rails_semantic_logger#60]
### Environment

ruby 2.4.2-p198
Rails 5.1.5
semantic logger 4.2.0
Puma: Version 3.11.3 (ruby 2.4.2-p198), codename: Love Song

```
2018-03-21 15:13:51.224088 E [20407:puma 001 log_subscriber.rb:86] ActiveRecord::Base -- Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 2, expected 1) [
"/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activerecord-5.1.5/lib/active_record/log_subscriber.rb:45:in `type_casted_binds'", 
"/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb:33:in `sql'", 
"/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/subscriber.rb:99:in `finish'",
"/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/log_subscriber.rb:83:in `finish'", "/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:102:in `finish'",
"/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `block in finish'",
"/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `each'", "/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `finish'", "/Users/enrico/.rvm/gems/ruby-2.4.2@frontend/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'", 
```

**Comment by codebycliff** [comment]
I am getting this as well. Here is my information:

ruby 2.4.3p205
Rails 5.1.5
semantic logger 4.2.0
puma 3.11.3

```
2018-03-22 12:25:01.128746 E [8558:70360863543940 log_subscriber.rb:86] ActiveRecord::Base -- Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 2, expected 1) ["/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/log_subscriber.rb:45:in `type_casted_binds'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb:33:in `sql'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/subscriber.rb:99:in `finish'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/log_subscriber.rb:83:in `finish'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:102:in `finish'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `block in finish'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `each'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `finish'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:27:in `instrument'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:614:in `exec_no_cache'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `execute_and_clear'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:79:in `exec_query'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:371:in `select'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `block in select_all'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'", "/Users/cliff/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `cache_sql'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/querying.rb:39:in `find_by_sql'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/bullet-5.7.5/lib/bullet/active_record5.rb:25:in `find_by_sql'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation.rb:678:in `exec_queries'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation.rb:546:in `load'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation.rb:255:in `records'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/bullet-5.7.5/lib/bullet/active_record5.rb:50:in `records'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation/batches.rb:216:in `block in in_batches'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation/batches.rb:214:in `loop'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation/batches.rb:214:in `in_batches'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation/batches.rb:128:in `find_in_batches'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/relation/batches.rb:62:in `find_each'", "/Users/cliff/Code/shiftdsm/lha-ignite/app/workers/scheduled_job_worker.rb:6:in `perform'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:187:in `execute_job'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/ddtrace-0.11.3/lib/ddtrace/contrib/sidekiq/tracer.rb:36:in `block in call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/ddtrace-0.11.3/lib/ddtrace/tracer.rb:272:in `trace'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/ddtrace-0.11.3/lib/ddtrace/contrib/sidekiq/tracer.rb:29:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/dogstatsd-ruby-3.3.0/lib/datadog/statsd.rb:241:in `time'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-pro-4.0.1/lib/sidekiq/middleware/server/statsd.rb:40:in `block in call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/dogstatsd-ruby-3.3.0/lib/datadog/statsd.rb:333:in `batch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-pro-4.0.1/lib/sidekiq/pro/metrics.rb:167:in `block in batch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-pro-4.0.1/lib/sidekiq/pro/metrics.rb:167:in `batch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-pro-4.0.1/lib/sidekiq/middleware/server/statsd.rb:39:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:56:in `cache'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activerecord-5.1.5/lib/active_record/query_cache.rb:11:in `cache'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/server/active_record_cache.rb:6:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-pro-4.0.1/lib/sidekiq/batch/middleware.rb:54:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-ent-1.7.0/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:168:in `block in process'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/job_retry.rb:97:in `local'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/rails.rb:47:in `block in call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/execution_wrapper.rb:85:in `wrap'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/reloader.rb:68:in `block in wrap'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/execution_wrapper.rb:85:in `wrap'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/activesupport-5.1.5/lib/active_support/reloader.rb:67:in `wrap'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/rails.rb:46:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:199:in `stats'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/job_logger.rb:7:in `call'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/job_retry.rb:72:in `global'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:127:in `block in dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/logging.rb:48:in `with_context'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/logging.rb:42:in `with_job_hash_context'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:126:in `dispatch'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:167:in `process'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:85:in `process_one'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/processor.rb:73:in `run'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/util.rb:16:in `watchdog'", "/Users/cliff/.rvm/gems/ruby-2.4.3@ignite/gems/sidekiq-5.1.1/lib/sidekiq/util.rb:25:in `block in safe_thread'"]```

**Comment by codebycliff** [comment]
It looks like this has been fixed in master via https://github.com/rocketjob/rails_semantic_logger/commit/1dbacd223d49a9c9f67860a3d5f4c299384033cd. Are there any plans to release this fix?

**Comment by reidmorrison** [comment]
Rails Semantic Logger v4.2.1 has been released
