### ISSUE TITLE
Rails 3 Exception at Start Up

### ISSUE THREAD

**Issue by HunterMeyer** [rocketjob/rails_semantic_logger#70]
### Environment

* Ruby Version: *2.3.6*
* Rails Version: *3.2.22*
* Semantic Logger Version: *4.3*
* Rails Semantic Logger Version: *4.3*
* Other Application/framework names and versions (e.g. Puma, etc.).
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger: *No settings applied, simply add gem to Gemfile, `bundle install`, then boot with `rails s`*
* Full Stack Trace, if an exception is being raised:
```
=> Booting WEBrick
=> Rails 3.2.22.5 application starting in development on http://0.0.0.0:3005
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rails_semantic_logger-4.3.0/lib/rails_semantic_logger.rb:24:in `swap_subscriber': undefined method `subscribers' for ActiveSupport::LogSubscriber:Class (NoMethodError)
Did you mean?  log_subscribers
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rails_semantic_logger-4.3.0/lib/rails_semantic_logger/engine.rb:225:in `block in <class:Engine>'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/huntermeyer/Documents/L360Repos/legacy_dashboards/config/environment.rb:5:in `<top (required)>'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/huntermeyer/Documents/L360Repos/legacy_dashboards/config.ru:3:in `block in <main>'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from /Users/huntermeyer/Documents/L360Repos/legacy_dashboards/config.ru:in `new'
	from /Users/huntermeyer/Documents/L360Repos/legacy_dashboards/config.ru:in `<main>'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/server.rb:200:in `app'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/commands/server.rb:46:in `app'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/commands/server.rb:70:in `start'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/commands.rb:50:in `tap'
	from /Users/huntermeyer/.rvm/gems/ruby-2.3.6@legacy_dashboards/gems/railties-3.2.22.5/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:21:in `require'
	from script/rails:21:in `<main>'
```

Note:
* Issues reported here should be related to monkey patches applied to Rails to make it use Semantic Logger. 
* For other logging and appender related issues, please report the issue at [Semantic Logger](https://github.com/rocketjob/semantic_logger/issues.

### Expected Behavior

* Describe your expectation of how Semantic Logger should behave, perhaps by showing how the builtin Rails logger behaves: *The rails server should boot up.*

### Actual Behavior

* Describe or show the actual behavior: *The rails server does not boot up. Stack trace above.
[This line here](https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger.rb#L24) raises an error because `ActiveSupport::LogSubscriber` does not respond to `subscribers`. Furthermore, on [this line here](https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger.rb#L31), an instance of `ActiveSupport::LogSubscriber` does not respond to `patterns`.*

**Comment by HunterMeyer** [comment]
Used version 3.4.1 to resolve.
