### ISSUE TITLE
   15 /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:77: [BUG] Segmentation fault at 0x0000000000000050

### ISSUE THREAD

**Issue by rgaufman** [rocketjob/rails_semantic_logger#79]
### Environment

Provide at least:
* Ruby ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
* Rails 5.2.1
* Semantic Logger Version 4.3.0
* Rails Semantic Logger Version 4.3.1
* Other Application/framework names: Puma 3.12.0

Everything seems to work OK in the main rails process, but when I start action cable, like so, this is the exception I get:

```
$ bundle exec puma -p 28080 cable/config.ru   -C config/puma-cable.rb
[9919] Puma starting in cluster mode...
[9919] * Version 3.12.0 (ruby 2.5.1-p57), codename: Llamas in Pajamas
[9919] * Min threads: 16, max threads: 64
[9919] * Environment: development
[9919] * Process workers: 1
[9919] * Preloading application
/var/lib/gems/2.5.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:15: warning: method BaseHelpers#windows? is deprecated. Use Pry:Helpers::Platform.windows? instead
[9919] * Listening on tcp://0.0.0.0:28080
[9919] ! WARNING: Detected 2 Thread(s) started in app boot:
[9919] ! #<Thread:0x0000000004e4fe90@/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:67 sleep_forever> - /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:130:in `pop'
[9919] ! #<Thread:0x00000000081c1df0@/data/deployer/.bundle/ruby/2.5.0/xanview-mqtt-b2ff4d825ef6/vendor/paho.mqtt.ruby-master/lib/paho_mqtt/client.rb:129 sleep> - /data/deployer/.bundle/ruby/2.5.0/xanview-mqtt-b2ff4d825ef6/vendor/paho.mqtt.ruby-master/lib/paho_mqtt/client.rb:194:in `sleep'
[9919] Use Ctrl-C to stop
I, [2018-11-08T20:20:17.875684 #9928]  INFO -- : Installing Puma worker loop.
[9919] - Worker 0 (pid: 9928) booted, phase: 0
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:77: [BUG] Segmentation fault at 0x0000000000000050
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0020 p:---- s:0155 e:000154 CFUNC  :push
c:0019 p:0009 s:0150 e:000149 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:77
c:0018 p:0024 s:0145 e:000144 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/processor.rb:38
c:0017 p:0048 s:0140 e:000139 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/logger.rb:38
c:0016 p:0150 s:0132 e:000131 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/base.rb:334
c:0015 p:0037 s:0120 e:000119 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/base.rb:84
c:0014 p:0011 s:0112 e:000111 BLOCK  /var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/tagged_logger_proxy.rb:38
c:0013 p:0074 s:0109 e:000108 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/semantic_logger.rb:340
c:0012 p:0123 s:0102 e:000101 METHOD /var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/base.rb:199
c:0011 p:0026 s:0094 e:000093 METHOD /var/lib/gems/2.5.0/gems/rails_semantic_logger-4.3.1/lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:8
c:0010 p:0008 s:0087 e:000086 METHOD /var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/tagged_logger_proxy.rb:38
c:0009 p:0009 s:0081 e:000080 BLOCK  /var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/tagged_logger_proxy.rb:32 [FINISH]
c:0008 p:0011 s:0077 e:000076 METHOD /var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/base.rb:70
c:0007 p:0024 s:0073 E:001ae8 METHOD /var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/server/base.rb:30
c:0006 p:0026 s:0068 E:001b58 METHOD /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225
c:0005 p:0258 s:0063 E:001c68 METHOD /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658
c:0004 p:0026 s:0038 E:001d10 METHOD /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472
c:0003 p:0065 s:0026 E:001db8 BLOCK  /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332 [FINISH]
c:0002 p:0125 s:0016 E:001e70 BLOCK  /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/server/base.rb:30:in `call'
/var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/base.rb:70:in `process'
/var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/tagged_logger_proxy.rb:32:in `block (2 levels) in <class:TaggedLoggerProxy>'
/var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/tagged_logger_proxy.rb:38:in `log'
/var/lib/gems/2.5.0/gems/rails_semantic_logger-4.3.1/lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:8:in `tag'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/base.rb:199:in `tagged'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/semantic_logger.rb:340:in `tagged'
/var/lib/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/tagged_logger_proxy.rb:38:in `block in log'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/base.rb:84:in `info'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/base.rb:334:in `log_internal'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/logger.rb:38:in `log'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/processor.rb:38:in `<<'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:77:in `log'
/var/lib/gems/2.5.0/gems/semantic_logger-4.3.0/lib/semantic_logger/appender/async.rb:77:in `push'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f1874977342 RBP: 0x0000000004f66670 RSP: 0x00007f186ae22210
 RAX: 0x0000000000000000 RBX: 0x00007f186e663360 RCX: 0x0000000004a65118
 RDX: 0x00007f186e663368 RDI: 0x0000000004f66670 RSI: 0x00007f186e6632f0
  R8: 0x0000000004e49930  R9: 0x0000000000000000 R10: 0x0000000000000000
 R11: 0x0000000000000001 R12: 0x00007f18601b3350 R13: 0x0000000004e4ff80
 R14: 0x00007f1874caff48 R15: 0x0000000000000001 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b95c5) [0x7f18749b95c5]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b97fc) [0x7f18749b97fc]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1874885574) [0x7f1874885574]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1874949e72) [0x7f1874949e72]
/lib/x86_64-linux-gnu/libc.so.6(0x7f18744684b0) [0x7f18744684b0]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1874977342) [0x7f1874977342]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f1874978a22) [0x7f1874978a22]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749a29a4) [0x7f18749a29a4]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749a6c97) [0x7f18749a6c97]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749ac6f7) [0x7f18749ac6f7]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749acf8f) [0x7f18749acf8f]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749aef24) [0x7f18749aef24]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b1bf3) [0x7f18749b1bf3]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749a8e27) [0x7f18749a8e27]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749ac6f7) [0x7f18749ac6f7]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b1094) [0x7f18749b1094]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b112b) [0x7f18749b112b]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b1474) [0x7f18749b1474]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b1bf3) [0x7f18749b1bf3]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749a8e27) [0x7f18749a8e27]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749ac6f7) [0x7f18749ac6f7]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b1094) [0x7f18749b1094]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f18749b112b) [0x7f18749b112b]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f187497b63f) [0x7f187497b63f]
/usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5(0x7f187497b9d3) [0x7f187497b9d3]
/lib/x86_64-linux-gnu/libpthread.so.0(start_thread+0xca) [0x7f187421d6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f187453a41d]

-- Other runtime information -----------------------------------------------

* Loaded script: puma: cluster worker 0: 9919 [current]

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /usr/lib/x86_64-linux-gnu/ruby/2.5.0/enc/encdb.so
    5 /usr/lib/x86_64-linux-gnu/ruby/2.5.0/enc/trans/transdb.so
    6 /usr/lib/x86_64-linux-gnu/ruby/2.5.0/rbconfig.rb
    7 /usr/lib/ruby/2.5.0/rubygems/compatibility.rb
    8 /usr/lib/ruby/2.5.0/rubygems/defaults.rb
    9 /usr/lib/ruby/2.5.0/rubygems/deprecate.rb
   10 /usr/lib/ruby/2.5.0/rubygems/errors.rb
   11 /usr/lib/ruby/2.5.0/rubygems/version.rb
   12 /usr/lib/ruby/2.5.0/rubygems/requirement.rb
   13 /usr/lib/ruby/2.5.0/rubygems/platform.rb
   14 /usr/lib/ruby/2.5.0/rubygems/basic_specification.rb
   15 /usr/lib/ruby/2.5.0/rubygems/stub_specification.rb
   16 /usr/lib/ruby/2.5.0/rubygems/util/list.rb
   17 /usr/lib/x86_64-linux-gnu/ruby/2.5.0/stringio.so
   18 /usr/lib/ruby/2.5.0/uri/rfc2396_parser.rb
   19 /usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb
   20 /usr/lib/ruby/2.5.0/uri/common.rb
   21 /usr/lib/ruby/2.5.0/uri/generic.rb
   22 /usr/lib/ruby/2.5.0/uri/ftp.rb
   23 /usr/lib/ruby/2.5.0/uri/http.rb
   24 /usr/lib/ruby/2.5.0/uri/https.rb
   25 /usr/lib/ruby/2.5.0/uri/ldap.rb
   26 /usr/lib/ruby/2.5.0/uri/ldaps.rb
   27 /usr/lib/ruby/2.5.0/uri/mailto.rb
   28 /usr/lib/ruby/2.5.0/uri.rb
   29 /usr/lib/ruby/2.5.0/rubygems/specification.rb
   30 /usr/lib/ruby/2.5.0/rubygems/exceptions.rb
   31 /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
   32 /usr/lib/ruby/2.5.0/rubygems/dependency.rb
   33 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_gem.rb
   34 /usr/lib/ruby/2.5.0/monitor.rb
   35 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb
   36 /usr/lib/ruby/2.5.0/rubygems.rb
   37 /usr/lib/ruby/2.5.0/rubygems/path_support.rb
   38 /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/version.rb
   39 /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/compatibility_guard.rb
   40 /usr/lib/x86_64-linux-gnu/ruby/2.5.0/pathname.so
   41 /usr/lib/ruby/2.5.0/pathname.rb
   42 /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/constants.rb
   43 /usr/lib/ruby/2.5.0/rubygems/util.rb
   44 /usr/lib/ruby/2.5.0/rubygems/user_interaction.rb
   45 /usr/lib/x86_64-linux-gnu/ruby/2.5.0/etc.so
   46 /usr/lib/ruby/2.5.0/rubygems/config_file.rb
   47 /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/rubygems_integration.rb
   48 /var/lib/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/current_ruby.rb
...
...
...
7f1873b63000-7f1873d62000 ---p 00009000 fd:01 1183111                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f1873d62000-7f1873d63000 r--p 00008000 fd:01 1183111                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f1873d63000-7f1873d64000 rw-p 00009000 fd:01 1183111                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f1873d64000-7f1873d92000 rw-p 00000000 00:00 0 
7f1873d92000-7f1873d95000 r-xp 00000000 fd:01 1182429                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f1873d95000-7f1873f94000 ---p 00003000 fd:01 1182429                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f1873f94000-7f1873f95000 r--p 00002000 fd:01 1182429                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f1873f95000-7f1873f96000 rw-p 00003000 fd:01 1182429                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f1873f96000-7f1874015000 r-xp 00000000 fd:01 3671563                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f1874015000-7f1874214000 ---p 0007f000 fd:01 3671563                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f1874214000-7f1874215000 r--p 0007e000 fd:01 3671563                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f1874215000-7f1874216000 rw-p 0007f000 fd:01 3671563                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f1874216000-7f187422e000 r-xp 00000000 fd:01 1182422                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f187422e000-7f187442d000 ---p 00018000 fd:01 1182422                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f187442d000-7f187442e000 r--p 00017000 fd:01 1182422                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f187442e000-7f187442f000 rw-p 00018000 fd:01 1182422                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f187442f000-7f1874433000 rw-p 00000000 00:00 0 
7f1874433000-7f18745f3000 r-xp 00000000 fd:01 1182424                    /lib/x86_64-linux-gnu/libc-2.23.so
7f18745f3000-7f18747f3000 ---p 001c0000 fd:01 1182424                    /lib/x86_64-linux-gnu/libc-2.23.so
7f18747f3000-7f18747f7000 r--p 001c0000 fd:01 1182424                    /lib/x86_64-linux-gnu/libc-2.23.so
7f18747f7000-7f18747f9000 rw-p 001c4000 fd:01 1182424                    /lib/x86_64-linux-gnu/libc-2.23.so
7f18747f9000-7f18747fd000 rw-p 00000000 00:00 0 
7f18747fd000-7f1874a9a000 r-xp 00000000 fd:01 3673836                    /usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5.1
7f1874a9a000-7f1874c99000 ---p 0029d000 fd:01 3673836                    /usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5.1
7f1874c99000-7f1874c9f000 r--p 0029c000 fd:01 3673836                    /usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5.1
7f1874c9f000-7f1874ca0000 rw-p 002a2000 fd:01 3673836                    /usr/lib/x86_64-linux-gnu/libruby-2.5.so.2.5.1
7f1874ca0000-7f1874cb0000 rw-p 00000000 00:00 0 
7f1874cb0000-7f1874cd6000 r-xp 00000000 fd:01 1179884                    /lib/x86_64-linux-gnu/ld-2.23.so
7f1874d9d000-7f1874dbf000 r--s 00000000 fd:01 1182422                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f1874dbf000-7f1874dc1000 r--s 00000000 fd:01 3673881                    /usr/bin/ruby2.5
7f1874dc1000-7f1874ec8000 rw-p 00000000 00:00 0 
7f1874ec9000-7f1874eca000 r-xp 00000000 00:00 0 
7f1874eca000-7f1874ed1000 r--s 00000000 fd:01 3675014                    /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f1874ed1000-7f1874ed2000 ---p 00000000 00:00 0 
7f1874ed2000-7f1874ed5000 rw-p 00000000 00:00 0 
7f1874ed5000-7f1874ed6000 r--p 00025000 fd:01 1179884                    /lib/x86_64-linux-gnu/ld-2.23.so
7f1874ed6000-7f1874ed7000 rw-p 00026000 fd:01 1179884                    /lib/x86_64-linux-gnu/ld-2.23.so
7f1874ed7000-7f1874ed8000 rw-p 00000000 00:00 0 
7ffe1f80c000-7ffe2000b000 rw-p 00000000 00:00 0                          [stack]
7ffe201a1000-7ffe201a4000 r--p 00000000 00:00 0                          [vvar]
7ffe201a4000-7ffe201a6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[9919] - Gracefully shutting down workers...
[9919] === puma shutdown: 2018-11-08 20:21:01 +0000 ===
[9919] - Goodbye!
```

(Note I had to crop some of the output as it was longer than the maximum allowed body)

### Expected Behavior
It should not cause a segmentation error

### Actual Behavior
It causes a segmentation error

Any ideas?

**Comment by rgaufman** [comment]
Adding:   SemanticLogger::Processor.instance.instance_variable_set(:@queue, Queue.new) to the on_worker_boot block fixed the problem! 

```
on_worker_boot do
  # Re-open appenders after forking the process
  SemanticLogger::Processor.instance.instance_variable_set(:@queue, Queue.new)
  SemanticLogger.reopen
end
```
